# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 99ecb93b8ef989dba2a443132fdc32a0b1803b7e5cc8992347fadc984709001fd00007d0a999c9f36075bcd8683b6f2522635cad2e25f32b2c12b34fbbe2049e

test:
  secret_key_base: 76d07d31bfc71b600e9d75633db9b00e6640f5092bebaa535d60a2f99594f61333e0061fd05c6e41d56587f7fbd1a788dc66eaa01cd20f1c8d34e2a4a9e23034

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
